### PR TITLE
Dependencies: Update to urllib3 2.x

### PR DESCRIPTION
**Pull request by amotl**
This patch makes the test cases compatible with the upcoming urllib3 version 2.x.

/cc @hramezani

### CODE REVIEW

**Comment by amotl** [comment]
According to [^1], the v2.0 migration guide can be found at [^2].

[^1]: https://github.com/urllib3/urllib3/releases/tag/2.0.0a2
[^2]: https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html

**Comment by amotl** [comment]
> ### What are the important changes?
>
> - Removed support for verifying certificate hostnames via `commonName`, now only `subjectAltName` is used.

Here we go. The exception is clearly related to this important change. We will have to update the certificates used for testing, at [./src/crate/client/pki](https://github.com/crate/crate-python/tree/0.28.0/src/crate/client/pki).

```python
crate.client.exceptions.ConnectionError: Server not available, exception: HTTPSConnectionPool(host='localhost', port=65534): 
Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: 
Hostname mismatch, certificate is not valid for 'localhost'. (_ssl.c:997)")))
```

**Comment by amotl** [comment]
I also just discovered that urllib3 1.x already issues a corresponding warning:

> SubjectAltNameWarning: Certificate for localhost has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/urllib3/urllib3/issues/497 for details.)

**Comment by amotl** [comment]
With d7c69fe, the X.509 certificates used for testing have been re-generated to use the `subjectAltName` attribute, as required.

**Review by hammerhead — APPROVED** [review]

**Review by BaurzhanSakhariev — APPROVED** [review]

**Pull request merged**
