### PR TITLE
Add backoff_factor in connection to configure retry interval

### PR DESCRIPTION
**Pull request by mfussenegger**
Squashed version of https://github.com/crate/crate-python/pull/342 with
some style fixes.

Cannot push to the fork, so created a new PR.

### CODE REVIEW

**Comment by daminichopra** [comment]
Hi @mfussenegger @autophagy , Thanks for merging and closing PR. I just want to confirm that when the new release for cratedb version 4.1.4 will be there. Thank you :)

**Comment by mfussenegger** [comment]
> Hi @mfussenegger @autophagy , Thanks for merging and closing PR. I just want to confirm that when the new release for cratedb version 4.1.4 will be there. Thank you :)

crate-python releases are independent of CrateDB releases. I guess we could make a release soonish.

**Comment by daminichopra** [comment]
Hi @mfussenegger , There is an [Issue](https://github.com/smartsdk/ngsi-timeseries-api/issues/242) which is dependent on release of cratedb verion 4.1.4. Can u Please confirm or give some estimate time by when new release will be there. Thank you

**Comment by autophagy** [comment]
@daminichopra CrateDB 4.1.4 was released on 20th of March. However, CrateDB is indepedent of the crate-python driver. The change you requested to this driver is available in 0.24.0 of the crate python driver. You can install this with:

```
pip install -U crate==0.24.0
```

**Pull request merged**
